version: '3'
services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - JWT_SECRET=secret
      - API_URL=http://backend:8080/api/
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=hWTq53KZp7rL4lPkTtnKknDlUBD4aYD2It/tmv6dOJw=
    depends_on:
      - backend
    networks:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/postit
    ports:
      - "8080:8080"
    networks:
      - backend
    depends_on:
      mysqldb:
        condition: service_healthy
  mysqldb:
    image: mysql:8.0.31
    container_name: mysqldb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postit
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
        - backend
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

networks:
  backend:

