version: '3'
services:
  mysql:
    image: mysql:8.0.31
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: postit
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - ./mysql:/var/lib/mysql
